### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by akeeman** [sendgrid/php-http-client#10]
#### Semantic versioning not (correctly) applied yet

Semantic versioning is handy for, you know, lots of reasons. See [semver.org](http://semver.org/). Let's use it here too!

##### Background
Version 3.2.0 is not fully bc with 3.1.0, resulting in [upgrade problems](https://github.com/sendgrid/sendgrid-php/pull/295) in, for instance, [sendgrid/sendgrid-php](https://github.com/sendgrid/sendgrid-php). As long as these things can happen, specific versions have to be referenced in those library's composer.json file. It would be nice to freely be able to upgrade within major versions.

How do you guys think about this?

**Comment by thinkingserious** [comment]
Hello @akeeman,

We are following (trying to) semantic versioning; however, it looks like I made a mistake with this release and did not catch the broken backwards compatibility. 

Thanks for submitting the pull requests.! I'll merge the other one once it's updated.
