### ISSUE TITLE
Implement auto-deploy to package manager

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/php-http-client#107]
#### Issue Summary

When all tests on the master branch pass in Travis CI, we would like to auto-deploy the release to the package manager.

Before writing any code, we suggest you review our `CONTRIBUTING.md` file and propose your solution for discussion here in the comments. Thank you!

#### Aceptance Criteria

* when Travis CI passes all tests on the master branch we auto-deploy to the package manager
* the version is determined by the `CHANGELOG.md`

**Comment by mauricetmeyer** [comment]
I would look into this later today.

My solution would work similarly to the one I proposed already to nodejs-http-client [#91](https://github.com/sendgrid/nodejs-http-client/pull/91), but would use a different deploy provider for the final step. This means I would like to reuse the nodejs script to get the version from the ```CHANGELOG.md```.

**Comment by childish-sambino** [comment]
Closing as Packagist has already been configured to release using webhooks.
