### ISSUE TITLE
Private members make library non-extensible

### ISSUE THREAD

**Issue by routinet** [sendgrid/php-http-client#129]
Due to the use of private members, the Client class cannot be extended into a custom class in my application.  I am assuming extensibility is desirable since many of the properties are marked as protected.  Changing the private members to be protected should suffice.

**Comment by thinkingserious** [comment]
Hello @routinet,

Would you be up to submitting a PR?

With Best Regards,

Elmer

**Comment by routinet** [comment]
Sure thing... I'll sort that out as soon as I'm back at my desk.  

I added a few other features to fit my particular uses.  Would you like to include any of these ideas?
 - auto-prefix the protocol to the host, if necessary (http/s)
 - add boolean property to disable SSL
 - add string property to provide a prefix for the API path

**Comment by routinet** [comment]
As this has been addressed in later commits, this issue can be closed.
