### ISSUE TITLE
Client class does not translate body parameters for GET requests

### ISSUE THREAD

**Issue by routinet** [sendgrid/php-http-client#146]
Feature request.

The Client class makes no translation of the body parameter into query string parameters when a GET request is made.  When a GET request is made, developers are currently required to build their own query string and pass it to the client as part of the url parameter.  Having the client object do the translation would make for a smoother developer experience, and ensures both calls follow the same pattern.

**Comment by eshanholtz** [comment]
Hi @routinet 

The Client class does in fact translate an array of query parameters into the relevant query string. Please refer to our [quick start guide])(https://github.com/sendgrid/php-http-client#quick-start) on how to pass query parameters to your request. The first example (the GET example) does not include query parameters, but the second example (the POST) example, does include this use case and is used in the same way for GET requests. For a more concrete example of a GET request with query parameters, please [refer to our example](https://github.com/sendgrid/php-http-client/blob/main/examples/example.php#L17).
