### ISSUE TITLE
How to manually install sendgrid/php-http-client

### ISSUE THREAD

**Issue by howardb3115** [sendgrid/php-http-client#20]
I am unable to use the 'compose install' to install this or the sendgrid/sendgrid-php api.  The sendgrid-php api had manual installation instructions, but this package does not.

Since this api is required for sendgrid/sendgrid-php would you please amend the installation instructions to also include a manual option, including a link to download this package, where is the best place to place the unzipped package, and the actual steps needed to manually install this package.

Thank you,
Howard Brown

**Comment by howardb3115** [comment]
Oh, and in the require statement what does __DIR__ mean, and would this be the value that I'd use if I put this package's directory in the vendors directory?

**Comment by thinkingserious** [comment]
Hello @howardb3115,

I have added this issue to our backlog for implementation.

If you are using sendgrid/sendgrid-php, then you do not need to manually install this library as it's included as a dependency.

[Here](http://php.net/manual/en/language.constants.predefined.php) is a description of the magic constant `__DIR__`.

With Best Regards,

Elmer

**Comment by jqturner** [comment]
It is Nov 2019.  Working in php (v7.3) on GoDaddy cPanel - Ultimate Linux shared hosting.
Relatively new at trying to get SendGrid working with my GoDaddy shared hosting account.   SendGrid was preinstalled on my public-html directory (example: public-html/sendgridapi/..et.al.).  So looks like all the required SendGrid files are there.  When I include a "require " statement in my php code, and run it, I get an error "public_html/sendgridapi/vendor/autoload.php) - failed to open stream".  I need some help getting past this... thanks.
