### ISSUE TITLE
Update .md files for SEO-ness

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/php-http-client#34]
We received an awesome PR for #hacktoberfest on our [ruby library](https://github.com/sendgrid/sendgrid-ruby/pull/220)
We would love to see the same thing on the README in this repo as well.
Please replace the "-" with "_"  in README, CONTRIBUTING, USE_CASES, USAGE files.

Thanks and happy Hacktoberfest!!

**Comment by positronek** [comment]
Submitted PR for diff. USE_CASES and USAGE .md files do not seem to exist in this repository. Also I replaced the "_" with the "-" as I believe that was the goal, similar to the ruby library.
