### ISSUE TITLE
Unable to use both php-http-client and sendgrid-php within the same application due to clashing class names

### ISSUE THREAD

**Issue by leesto** [sendgrid/php-http-client#4]
#### Issue Summary

Within the same application, if both php-http-client and sendgrid-php are managed via composer and loaded into the application using the autoloader, because both libraries contain a SendGrid\Response class with different properties, it causes an error

#### Steps to Reproduce
1. Create an application or library and through composer require the latest versions of php-http-client and sendgrid-php
2. Use the composer autoloader to allow use of the sendgrid libraries within your own code
3. Make a call to the web API using php-http-client (for example, to retrieve all templates). This works fine and returns a response.
4. Send an email using the \SendGrid class in sendgrid-php. The email sends, but on trying to return a response, it errors:

`PHP Notice:  Undefined property: SendGrid\Response::$code in /Users/lee.stone/components/Email/vendor/sendgrid/sendgrid/lib/SendGrid.php on line 119`

`PHP Notice:  Undefined property: SendGrid\Response::$raw_body in /Users/lee.stone/components/Email/vendor/sendgrid/sendgrid/lib/SendGrid.php on line 120`

This in turn causes a SendGrid Exception to be thrown:
`SendGrid\Exception:  in /Users/lee.stone/components/Email/vendor/sendgrid/sendgrid/lib/SendGrid.php on line 120`

This is caused as both libraries have a SendGrid\Response Class.

As the php-http-client doesn't support sending emails, but is seen as the replacement for interacting with the Web API compared to the client in sendgrid-php, I would expect to be able to use both libraries within the same application so I can query data and send emails. One of the response classes may need its namespace to be changed to support this.

#### Technical details:

* php-http-client Version: 1.0.1
* PHP Version: 5.4

**Comment by thinkingserious** [comment]
Thanks for the detailed issue report @leesto!

We are currently re-writing the PHP library and this client is meant for that new version. It should be released very soon along with our new v3 mail endpoint. Please watch the other repo for updates and thanks for your support!

Since this issue goes away with the new library, I will close this one.
