### ISSUE TITLE
Namespacing still does not work

### ISSUE THREAD

**Issue by lfjeff** [sendgrid/php-http-client#5]
#### Issue Summary

Have you actually tested this code using composer and namespaces?

It should be possible to do the following:

`require 'vendor/autoload.php';
use SendGrid\Client;

$client = new SendGrid\Client(...);`

However, this does not work.  It is still necessary to explicitly include the file:

`require 'vendor/sendgrid/php-http-client/lib/SendGrid/client.php';

$client = new SendGrid\Client(...);`

It would be nice if you could fix your code so it works the same way as other PHP packages.

**Comment by thinkingserious** [comment]
Hello @lfjeff,

Thanks for letting us know and I hope we can help you get going quickly.

Unfortunately, I can not reproduce your error. 

Could you please give me the step by step details on how you arrived at your conclusion and any errors you received along the way? It might also be helpful if you can provide your composer.json and your source code.

Here is the code that I have working locally:

test.php:

```php
<?php
require __DIR__ . '/vendor/autoload.php';
$config = new SendGrid\Config(getcwd(), '.env');
$api_key = getenv('SENDGRID_API_KEY');
$headers = array(
    'Content-Type: application/json',
    'Authorization: Bearer '.$api_key
);
$headers = array(
    'Content-Type: application/json',
    'Authorization: Bearer '.$api_key
);
$client = new SendGrid\Client('https://api.sendgrid.com', $headers, '/v3', null);

// GET Collection
$query_params = array('limit' => 100, 'offset' => 0);
$request_headers = array('X-Mock: 200');
$response = $client->api_keys()->get(null, $query_params, $request_headers);
echo $response->statusCode();
echo $response->responseBody();
echo $response->responseHeaders();
// POST
$request_body = array(
        'name' => 'My PHP API Key',
        'scopes' => array(
            'mail.send',
            'alerts.create',
            'alerts.read'
        )
);
$response = $client->api_keys()->post($request_body);
echo $response->statusCode();
echo $response->responseBody();
echo $response->responseHeaders();
$response_body = json_decode($response->responseBody());
$api_key_id = $response_body->api_key_id;

// GET Single
$response = $client->version('/v3')->api_keys()->_($api_key_id)->get();
echo $response->statusCode();
echo $response->responseBody();
echo $response->responseHeaders();

// PATCH
$request_body = array(
        'name' => 'A New Hope'
);
$response = $client->api_keys()->_($api_key_id)->patch($request_body);
echo $response->statusCode();
echo $response->responseBody();
echo $response->responseHeaders();

// PUT
$request_body = array(
        'name' => 'A New Hope',
        'scopes' => array(
            'user.profile.read',
            'user.profile.update'
        )
);
$response = $client->api_keys()->_($api_key_id)->put($request_body);
echo $response->statusCode();
echo $response->responseBody();
echo $response->responseHeaders();

// DELETE
$response = $client->api_keys()->_($api_key_id)->delete();
echo $response->statusCode();
echo $response->responseBody();
echo $response->responseHeaders();
?>
```
composer.json
```javascript
{
    "require": {
        "sendgrid/php-http-client": "1.*"
    }
}
```

With Best Regards,

Elmer

**Comment by edpittol** [comment]
I got this error in PHP 5.5. In the 5.6, works fine.

**Comment by lfjeff** [comment]
I'm using PHP 5.4.

I just switched to using Guzzle to talk to the API.  After playing with the Sendgrid API, I don't see much advantage to using it vs Guzzle.

**Comment by edpittol** [comment]
I never used Guzzle. But really, seems a good solution. Create a interface with any web service API. For a quick fix in my project, I used the version_compare function :(.

**Comment by thinkingserious** [comment]
@edpittol @lfjeff 

I was able to track down the issue, naming the file client.php instead of Client.php breaks the autoloader. However, on OS X, the case is ignored and thus it worked in my local development environment.

Also, I have some good news. Our new PHP library (which depends on this client) is now ready for public beta, you can find it here: https://github.com/sendgrid/sendgrid-php/tree/v3beta

Thank you for taking the time to provide your feedback!

BTW, we got rid of Guzzle support to use PHPs native libraries because we had many tickets where a particular framework would not work because of the Guzzle dependency. Depending on the framework, you would need to use a particular Guzzle version. In the official SendGrid PHP client, currently we only depend on this HTTP client, but we will add functionality where you can inject whatever HTTP client you want.

Please let me know if you have any further questions.
