### ISSUE TITLE
Document and throw an error to help people with CURLOPT_SSL_VERIFYPEER issues

### ISSUE THREAD

**Issue by akaSyntaax** [sendgrid/php-http-client#90]
#### Issue Summary

If I try to send an email trough the sendgrid-php api I only get a timeout after a while, the email doesn't get send. There are no errors thrown. This issue happened after an update from version 3.9.0 to 3.9.1.

#### Steps to Reproduce

1. Try to send a simple email (from the sendgrid-php repository for example)

#### Technical details:

* php-http-client Version: 3.9.1 (commit 56d046a)
* PHP Version: 7.1.15-1

**Comment by thinkingserious** [comment]
Hello @akaSyntaax,

I believe the issue is probably due to this: https://github.com/sendgrid/php-http-client/blob/master/lib/Client.php#L189

If you set that value to false it will work, but that would be insecure, per this issue: https://github.com/sendgrid/php-http-client/issues/81. The better fix would be to update your *.pem path, like so: https://stackoverflow.com/questions/18971983/curl-requires-curlopt-ssl-verifypeer-false

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
That said, we need to update the SDK to throw an error that specifically states the peer is not verified.

**Comment by akaSyntaax** [comment]
Hello @thinkingserious ,

thank you for your fast response! I updated my cacert.pem path and tried to send an email again. This time I got an authorization failed as response so I created a new API key and this time I got the following error: "The provided authorization grant is invalid, expired, or revoked". Then I tried to supply the API code directly in the \SendGrid constructor and now it is working fine. My question now is why it didn't work if I simply provide the API key from a constant? I printed out this constant and it is giving out the right API key.
For example:

Returns "The provided authorization grant is invalid, expired, or revoked":
`$sg = new \SendGrid(Config::SENDGRID_API_KEY);`

Works:
`$sg = new \SendGrid('##############################);`

Thank you in advance,
Hendrik (akaSyntaax)

**Comment by akaSyntaax** [comment]
Hello @thinkingserious,

I updated my *.pem path as you said and this resolved my issue.
Thank you very much!

Kind regards,
Hendrik Lübke (akaSyntaax)

**Comment by thinkingserious** [comment]
Thanks for the follow up @akaSyntaax.

I'm re-opening so we can properly document this and create a helpful error message.

**Comment by colinodell** [comment]
I have introduced three possible PRs to address this:

Two PRs to alert the user to an issue:

 - #103 will throw an exception which can be caught and handled accordingly
 - #104 will trigger an `E_USER_ERROR`

One PR (#105) to help users whose PHP instance is having trouble locating the CA bundle.
